Common tools lib created for shared code
navferty/NavfertyExcelAddIn pull request #109
Opened 2022-02-04 22:22 UTC by uom42

Do not merge, just for test use

2022-02-05 12:06 UTC, navferty requested changes

2022-02-05 12:06 UTC, navferty commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/ExchangeRatesDataProviderBaase.cs
> +	internal abstract class ExchangeRatesDataProviderBaase
`Baase` - typo?

2022-02-05 12:06 UTC, navferty commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/ExchangeRatesDataProviderBaase.cs
> +			if (ex1 != null && ex2 == null)
Возможно, тут должна быть проверка на `webRowsForPrevDay?.Any()` ?

2022-02-05 12:06 UTC, navferty commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/ExchangeRatesDataProviderBaase.cs
> +				throw ex1 ?? new Exception(UIStrings.CurrencyExchangeRates_Error_Network);
null coalescing выглядит лишним, `ex1 != null`

2022-02-05 12:06 UTC, navferty commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/ExchangeRatesDataProviderBaase.cs
> +			if (null != ex1 || !webRowsForDay.Any())
Возможно, лучше оставить только одну проверку на `!webRowsForDay.Any()` ? В случае, если `DownloadWebResultRowsForDate` не выбросит исключение, но вернёт null, тоже имеет смысл запросить за вчера

2022-02-05 12:06 UTC, navferty commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/NBU/NBUProvider.cs
> +				Content.ReadAsStringAsync();
Я бы предложил отдельно добавить явную проверку на код статуса ответа, а также try-catch. В случае недоступности api можно показать более детальное сообщение, что удалённый сервер недоступен. Да и в случае неожиданного кода ответа, также оповестить что сервер отдал что-то не то

2022-02-05 13:17 UTC, uom42 commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/ExchangeRatesDataProviderBaase.cs
> +	internal abstract class ExchangeRatesDataProviderBaase
ok

2022-02-05 13:20 UTC, uom42 commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/ExchangeRatesDataProviderBaase.cs
> +			if (ex1 != null && ex2 == null)
ok

2022-02-05 13:40 UTC, uom42 commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/DataProviders/ExchangeRatesDataProviderBaase.cs
> +				throw ex1 ?? new Exception(UIStrings.CurrencyExchangeRates_Error_Network);
иногда, у ЕЦБ например, возвращается пустой xml, без ошибки, 
например как раз когда нет данных на текущий день. 
поэтому Ex1 и Ex2 могут оказаться null. 

Я переделаю логику, чтобы если нет ни одной строки - возникала ошибка.

2022-02-05 21:48 UTC, navferty commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/ExchangeRateRecord.cs
> +					   select r).ToArray();
ToArray лишний

2022-02-05 21:48 UTC, navferty commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/Providers/ExchangeRatesProviderBase.cs
> +			Logger.Debug($"Starting Web query attempt #{nTry}, Date: '{sDate}'...");
Можно определить форматирование даты прямо в интерполированной строке:

```suggestion
			Logger.Debug($"Starting Web query attempt #{nTry}, Date: '{sDate:yyyy-MM-dd}'...");

```

2022-02-05 21:48 UTC, navferty commented on NavfertyExcelAddIn/Web/WebToolsBuilder.cs
> +			//			var weeee = Navferty.ExcelAddIn.Web.CurrencyExchangeRates.Providers.NBU.JsonExchangeRatesForDateRecord();
что-то лишнее)

2022-02-05 23:22 UTC, uom42 commented on Navferty.ExcelAddIn.Web/CurrencyExchangeRates/ExchangeRateRecord.cs
> +					   select r).ToArray();
Нет, не лишний, в параметрах функции передаётся Array, а не IEnumerable.
Я исправлю в заголовке функции на IEnumerable.

2022-02-06 00:06 UTC, uom42 commented
Finished

2022-02-06 11:26 UTC, navferty approved these changes

2022-02-06 11:32 UTC, merged